"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronDown, Edit3, FileImage, Newspaper, Plus, Search, Trash2, UploadCloud, X } from "lucide-react";

type Blog={id:string;title:string;slug:string;category:string;excerpt:string;content:string;featuredImage:string;author:string;tags:string;seoTitle:string;metaDescription:string;status:"Draft"|"Published";publishDate:string;createdAt?:string;updatedAt?:string};
const categories=["Assignments","Research","Teaching Practice","Student Guide","News"];
const emptyBlog=():Blog=>({id:"",title:"",slug:"",category:"Student Guide",excerpt:"",content:"",featuredImage:"",author:"",tags:"",seoTitle:"",metaDescription:"",status:"Draft",publishDate:new Date().toISOString().slice(0,10)});
const fieldClass="focus-ring w-full rounded-xl border border-[#d7e0e7] bg-white px-4 py-3 text-sm text-[#0b1f3a]";

async function upload(file:File|null){if(!file)return "";if(file.size>5*1024*1024)throw new Error("Featured image must be 5 MB or smaller.");const data=new FormData();data.set("file",file);const response=await fetch("/api/uploads",{method:"POST",body:data});const body=await response.json();if(!response.ok)throw new Error(body.error??"Image upload failed.");return body.url as string}

export function BlogStudio(){
  const [posts,setPosts]=useState<Blog[]>([]);const [draft,setDraft]=useState<Blog>(emptyBlog);const [editor,setEditor]=useState(false);const [image,setImage]=useState<File|null>(null);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const imageInput=useRef<HTMLInputElement>(null);
  useEffect(()=>{let active=true;fetch("/api/admin/blogs",{cache:"no-store"}).then(async response=>({ok:response.ok,body:await response.json()})).then(({ok,body})=>{if(!active)return;if(ok)setPosts(body);else setError(body.error??"Unable to load blog posts.");setLoading(false)});return()=>{active=false}},[]);
  const visible=useMemo(()=>posts.filter(post=>`${post.title} ${post.category} ${post.author} ${post.tags}`.toLowerCase().includes(query.toLowerCase())),[posts,query]);
  function set<K extends keyof Blog>(key:K,value:Blog[K]){setDraft(current=>({...current,[key]:value}))}
  function newPost(){setDraft(emptyBlog());setImage(null);setError("");setEditor(true)}
  function edit(post:Blog){setDraft({...post});setImage(null);setError("");setEditor(true)}
  async function remove(post:Blog){if(!window.confirm(`Delete “${post.title}”?`))return;const response=await fetch(`/api/admin/blogs?id=${encodeURIComponent(post.id)}`,{method:"DELETE"});if(response.ok){setPosts(current=>current.filter(item=>item.id!==post.id));setNotice("Blog post deleted.")}}
  async function save(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");try{const featuredImage=await upload(image)||draft.featuredImage;const payload={...draft,featuredImage};const response=await fetch("/api/admin/blogs",{method:draft.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to save blog post.");const stored=body as Blog;setPosts(current=>draft.id?current.map(post=>post.id===draft.id?stored:post):[stored,...current]);setEditor(false);setNotice(draft.id?"Blog post updated.":"Blog post created.")}catch(problem){setError(problem instanceof Error?problem.message:"Unable to save post.")}finally{setSaving(false)}}
  return <>
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#147a4b]">Publishing</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.045em] text-[#0b1f3a] md:text-4xl">Blog Studio</h1><p className="mt-2 text-sm leading-6 text-[#607086]">Write complete articles, prepare search metadata and manage publishing status.</p></div><button onClick={newPost} className="inline-flex items-center gap-2 rounded-xl bg-[#147a4b] px-5 py-3 text-sm font-bold text-white"><Plus size={18}/>Write article</button></div>
    <section className="mt-7 overflow-hidden rounded-2xl border border-[#dfe6ec] bg-white"><div className="border-b border-[#e5ebef] p-4"><label className="flex max-w-md items-center gap-3 rounded-xl bg-[#f4f7f9] px-4 py-3"><Search size={17} className="text-[#718094]"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search articles" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead><tr className="bg-[#f8fafb] text-[10px] font-extrabold uppercase tracking-[.09em] text-[#718094]"><th className="px-5 py-4">Article</th><th className="px-4 py-4">Category</th><th className="px-4 py-4">Author</th><th className="px-4 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{visible.map(post=><tr key={post.id} className="border-t border-[#edf1f4]"><td className="px-5 py-4"><p className="text-sm font-extrabold text-[#0b1f3a]">{post.title}</p><p className="mt-1 max-w-md truncate text-xs text-[#718094]">{post.excerpt}</p></td><td className="px-4 py-4 text-sm text-[#53657a]">{post.category}</td><td className="px-4 py-4 text-sm text-[#53657a]">{post.author}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${post.status==="Published"?"bg-[#eaf6ef] text-[#147a4b]":"bg-[#fff4e5] text-[#9a5b19]"}`}>{post.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button onClick={()=>edit(post)} className="grid size-9 place-items-center rounded-lg hover:bg-[#eaf6ef]"><Edit3 size={16}/></button><button onClick={()=>void remove(post)} className="grid size-9 place-items-center rounded-lg text-red-700 hover:bg-red-50"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{loading?<div className="grid min-h-52 place-items-center text-sm text-[#718094]">Loading articles…</div>:!visible.length?<div className="grid min-h-52 place-items-center text-center"><div><Newspaper className="mx-auto text-[#9aa6b3]"/><p className="mt-3 font-bold text-[#0b1f3a]">No articles yet</p><p className="mt-1 text-sm text-[#718094]">Write your first complete blog article.</p></div></div>:null}</div></section>
    {editor?<div className="fixed inset-0 z-[60] flex justify-end bg-[#071426]/55 backdrop-blur-[2px]" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)setEditor(false)}}><aside className="flex h-full w-full max-w-[900px] flex-col bg-[#f4f7f9] shadow-[-24px_0_70px_rgba(3,15,30,.24)]"><header className="flex items-center justify-between border-b border-[#dfe6ec] bg-white px-6 py-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#147a4b]">{draft.id?"Edit article":"New article"}</p><h2 className="mt-1 text-xl font-extrabold text-[#0b1f3a]">{draft.title||"Write blog article"}</h2></div><button onClick={()=>setEditor(false)} className="grid size-10 place-items-center rounded-xl border border-[#dfe6ec]"><X size={18}/></button></header><form onSubmit={save} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 space-y-5 overflow-y-auto p-5 md:p-6">
      <section className="grid gap-4 rounded-2xl border border-[#dfe6ec] bg-white p-5 md:grid-cols-2"><label className="grid gap-2 text-xs font-bold uppercase text-[#607086] md:col-span-2">Title<input required value={draft.title} onChange={event=>{const value=event.target.value;set("title",value);if(!draft.id)set("slug",value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""))}} className={fieldClass} placeholder="How to prepare an AIOU assignment"/></label><label className="grid gap-2 text-xs font-bold uppercase text-[#607086]">URL slug<input required value={draft.slug} onChange={event=>set("slug",event.target.value)} className={fieldClass}/></label><label className="grid gap-2 text-xs font-bold uppercase text-[#607086]">Category<span className="relative"><select value={draft.category} onChange={event=>set("category",event.target.value)} className={`${fieldClass} appearance-none`} >{categories.map(category=><option key={category}>{category}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2" size={15}/></span></label><label className="grid gap-2 text-xs font-bold uppercase text-[#607086]">Author<input required value={draft.author} onChange={event=>set("author",event.target.value)} className={fieldClass} placeholder="Editorial Team"/></label><label className="grid gap-2 text-xs font-bold uppercase text-[#607086]">Publish date<input type="date" value={draft.publishDate} onChange={event=>set("publishDate",event.target.value)} className={fieldClass}/></label><label className="grid gap-2 text-xs font-bold uppercase text-[#607086] md:col-span-2">Excerpt<textarea required rows={3} maxLength={300} value={draft.excerpt} onChange={event=>set("excerpt",event.target.value)} className={`${fieldClass} resize-y leading-6`} placeholder="Short summary shown on blog cards…"/></label></section>
      <section className="rounded-2xl border border-[#dfe6ec] bg-white p-5"><h3 className="text-sm font-extrabold text-[#0b1f3a]">Article body</h3><p className="mt-1 text-xs text-[#718094]">Write the complete article below. Use blank lines between sections.</p><textarea required rows={18} value={draft.content} onChange={event=>set("content",event.target.value)} className={`${fieldClass} mt-4 resize-y font-[Arial] leading-7`} placeholder={"Introduction…\n\nMain heading\nExplain the topic clearly…\n\nConclusion…"}/></section>
      <section className="grid gap-4 rounded-2xl border border-[#dfe6ec] bg-white p-5 md:grid-cols-2"><div><p className="mb-2 text-xs font-bold uppercase text-[#607086]">Featured image</p><button type="button" onClick={()=>imageInput.current?.click()} className="flex w-full items-center gap-3 rounded-xl border-2 border-dashed border-[#cfd9e1] bg-[#f8fafb] p-4 text-left"><span className="grid size-10 place-items-center rounded-xl bg-white text-[#147a4b]">{image?<FileImage size={18}/>:<UploadCloud size={18}/>}</span><span className="text-sm font-bold text-[#0b1f3a]">{image?.name||"Choose PNG or JPG"}</span><input ref={imageInput} hidden type="file" accept=".png,.jpg,.jpeg" onChange={event=>setImage(event.target.files?.[0]??null)}/></button></div><label className="grid gap-2 text-xs font-bold uppercase text-[#607086]">Tags<input value={draft.tags} onChange={event=>set("tags",event.target.value)} className={fieldClass} placeholder="assignments, writing, B.Ed"/></label></section>
      <section className="grid gap-4 rounded-2xl border border-[#dfe6ec] bg-white p-5"><h3 className="text-sm font-extrabold text-[#0b1f3a]">SEO and publishing</h3><label className="grid gap-2 text-xs font-bold uppercase text-[#607086]">SEO title<input value={draft.seoTitle} onChange={event=>set("seoTitle",event.target.value)} className={fieldClass}/></label><label className="grid gap-2 text-xs font-bold uppercase text-[#607086]">Meta description<textarea rows={3} maxLength={160} value={draft.metaDescription} onChange={event=>set("metaDescription",event.target.value)} className={`${fieldClass} resize-y`}/></label><label className="grid gap-2 text-xs font-bold uppercase text-[#607086]">Status<select value={draft.status} onChange={event=>set("status",event.target.value as Blog["status"])} className={fieldClass}><option>Draft</option><option>Published</option></select></label></section>
    </div><footer className="border-t border-[#dfe6ec] bg-white px-6 py-4"><div className="flex items-center justify-between gap-4">{error?<p className="text-xs font-bold text-red-700">{error}</p>:<p className="text-xs text-[#718094]">{draft.status==="Published"?"Article will be publicly eligible after saving.":"Article remains private as a draft."}</p>}<div className="ml-auto flex gap-3"><button type="button" onClick={()=>setEditor(false)} className="rounded-xl border border-[#d7e0e7] px-5 py-3 text-sm font-bold">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#147a4b] px-5 py-3 text-sm font-bold text-white"><Check size={17}/>{saving?"Saving…":"Save article"}</button></div></div></footer></form></aside></div>:null}
    {notice?<div className="fixed bottom-5 right-5 z-[80] rounded-xl bg-[#0b1f3a] px-4 py-3 text-sm font-bold text-white">{notice}</div>:null}
  </>;
}
