"use client";

import { useEffect, useMemo, useState } from "react";
import { RefreshCw, Search, ShieldCheck, UserRound, UserX } from "lucide-react";

type Customer={_id:string;name:string;email:string;phone?:string;status:"active"|"inactive";createdAt:string;updatedAt:string};

export function CustomerManager(){
  const [customers,setCustomers]=useState<Customer[]>([]);const [loading,setLoading]=useState(true);
  const [query,setQuery]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState("");
  async function load(){setLoading(true);setError("");const response=await fetch("/api/admin/customers",{cache:"no-store"});const body=await response.json();if(response.ok)setCustomers(body);else setError(body.error??"Unable to load customers.");setLoading(false)}
  useEffect(()=>{void load()},[]);
  const visible=useMemo(()=>customers.filter(customer=>`${customer.name} ${customer.email} ${customer.phone??""}`.toLowerCase().includes(query.toLowerCase())),[customers,query]);
  async function setStatus(customer:Customer,status:Customer["status"]){
    setSaving(customer._id);setError("");
    const response=await fetch("/api/admin/customers",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:customer._id,status})});
    const body=await response.json();if(response.ok)setCustomers(current=>current.map(item=>item._id===customer._id?body:item));else setError(body.error??"Unable to update customer.");setSaving("");
  }
  return <div><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#147a4b]">Customer portal</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.045em] text-[#0b1f3a] md:text-4xl">Customers</h1><p className="mt-2 text-sm leading-6 text-[#607086]">Review registered customers and suspend suspicious accounts without removing their history.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-[#d7e0e7] bg-white px-4 py-3 text-sm font-bold text-[#405169]"><RefreshCw size={17} className={loading?"animate-spin":""}/>Refresh</button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3">{[["Registered",customers.length,UserRound],["Active",customers.filter(x=>x.status==="active").length,ShieldCheck],["Suspended",customers.filter(x=>x.status==="inactive").length,UserX]].map(([label,value,Icon])=>{const I=Icon as typeof UserRound;return <div key={label as string} className="rounded-2xl border border-[#dfe6ec] bg-white p-5"><I size={19} className="text-[#147a4b]"/><p className="mt-4 text-3xl font-extrabold text-[#0b1f3a]">{value as number}</p><p className="mt-1 text-sm font-semibold text-[#718094]">{label as string}</p></div>})}</div>
    <section className="mt-6 overflow-hidden rounded-2xl border border-[#dfe6ec] bg-white"><div className="border-b border-[#e5ebef] p-4"><label className="flex max-w-md items-center gap-3 rounded-xl bg-[#f4f7f9] px-4 py-3 text-[#607086]"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search name, email or phone" className="min-w-0 flex-1 bg-transparent text-sm text-[#0b1f3a] outline-none"/></label></div>{error?<p className="border-b border-red-100 bg-red-50 px-5 py-3 text-sm font-semibold text-red-700">{error}</p>:null}<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="bg-[#f8fafb] text-[10px] font-extrabold uppercase tracking-[.09em] text-[#718094]"><th className="px-5 py-4">Customer</th><th className="px-4 py-4">Phone</th><th className="px-4 py-4">Registered</th><th className="px-4 py-4">Status</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody>{visible.map(customer=><tr key={customer._id} className="border-t border-[#edf1f4]"><td className="px-5 py-4"><p className="text-sm font-extrabold text-[#0b1f3a]">{customer.name}</p><p className="mt-1 text-xs text-[#718094]">{customer.email}</p></td><td className="px-4 py-4 text-sm text-[#53657a]">{customer.phone||"—"}</td><td className="px-4 py-4 text-sm text-[#53657a]">{new Intl.DateTimeFormat("en-PK",{day:"numeric",month:"short",year:"numeric"}).format(new Date(customer.createdAt))}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${customer.status==="active"?"bg-[#eaf6ef] text-[#147a4b]":"bg-red-50 text-red-700"}`}>{customer.status==="active"?"Active":"Suspended"}</span></td><td className="px-5 py-4 text-right"><button disabled={saving===customer._id} onClick={()=>void setStatus(customer,customer.status==="active"?"inactive":"active")} className={`rounded-lg px-3 py-2 text-xs font-bold ${customer.status==="active"?"border border-red-200 text-red-700 hover:bg-red-50":"bg-[#147a4b] text-white"}`}>{saving===customer._id?"Saving…":customer.status==="active"?"Suspend":"Reactivate"}</button></td></tr>)}</tbody></table>{loading?<div className="grid min-h-48 place-items-center"><RefreshCw className="animate-spin text-[#147a4b]"/></div>:!visible.length?<div className="grid min-h-48 place-items-center text-sm text-[#718094]">No customers found.</div>:null}</div></section>
  </div>;
}
