"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BookMarked, CalendarDays, CircleDollarSign, FilePlus2, FileText, GraduationCap, Newspaper, RefreshCw, ShoppingBag } from "lucide-react";
import { DashboardCard } from "./DashboardCard";

type Order={_id:string;studentName:string;courseCode:string;serviceType:string;price?:number;paymentStatus:string;orderStatus:string;createdAt:string};
type Material={id:string;status:string;downloads?:number};
type Generic={id:string;values:string[]};

export function LiveDashboard(){
  const [orders,setOrders]=useState<Order[]>([]);const [materials,setMaterials]=useState<Material[]>([]);
  const [programs,setPrograms]=useState<Generic[]>([]);const [courses,setCourses]=useState<Generic[]>([]);const [posts,setPosts]=useState<Generic[]>([]);
  const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);const results=await Promise.all(["/api/orders","/api/admin/materials","/api/admin/programs","/api/admin/courses","/api/admin/blog-posts"].map(url=>fetch(url,{cache:"no-store"}).then(async response=>response.ok?response.json():[])));setOrders(results[0]);setMaterials(results[1]);setPrograms(results[2]);setCourses(results[3]);setPosts(results[4]);setLoading(false)}
  useEffect(()=>{void load()},[]);
  const revenue=orders.filter(order=>order.paymentStatus==="paid").reduce((sum,order)=>sum+(Number(order.price)||0),0);
  const pending=orders.filter(order=>order.orderStatus==="new"||order.orderStatus==="waiting_for_payment").length;
  const downloads=materials.reduce((sum,material)=>sum+(Number(material.downloads)||0),0);
  const date=new Intl.DateTimeFormat("en-PK",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());
  return <>
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#147a4b]">{date}</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.045em] text-[#0b1f3a] md:text-4xl">Administration overview</h1><p className="mt-2 text-sm leading-6 text-[#607086]">All figures below are calculated from your stored records.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-[#d7e0e7] bg-white px-4 py-3 text-sm font-bold text-[#405169]"><RefreshCw size={17} className={loading?"animate-spin":""}/>Refresh data</button></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><DashboardCard label="Materials" value={String(materials.length)} icon={FileText} note={`${downloads.toLocaleString()} recorded downloads`} accent="green"/><DashboardCard label="Student orders" value={String(orders.length)} icon={ShoppingBag} note={`${pending} awaiting action`} accent="amber"/><DashboardCard label="Confirmed revenue" value={`PKR ${revenue.toLocaleString()}`} icon={CircleDollarSign} note="From orders marked Paid" accent="navy"/><DashboardCard label="Programs & courses" value={`${programs.length} / ${courses.length}`} icon={GraduationCap} note="Real configured records" accent="blue"/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><section className="overflow-hidden rounded-2xl border border-[#dfe6ec] bg-white"><div className="flex items-center justify-between border-b border-[#e8edf1] px-5 py-5"><div><h2 className="text-lg font-extrabold text-[#0b1f3a]">Recent real orders</h2><p className="mt-1 text-xs text-[#607086]">Latest student submissions</p></div><Link href="/admin/orders" className="text-xs font-bold text-[#147a4b]">View all</Link></div>{orders.length?<div className="divide-y divide-[#edf1f4]">{orders.slice(0,6).map(order=><Link href="/admin/orders" key={order._id} className="grid gap-2 px-5 py-4 hover:bg-[#fbfcfd] sm:grid-cols-[1fr_100px_150px]"><div><p className="text-sm font-extrabold text-[#0b1f3a]">{order.studentName}</p><p className="mt-1 text-xs text-[#718094]">{order.serviceType}</p></div><p className="text-sm font-bold text-[#405169]">{order.courseCode}</p><p className="text-xs font-bold text-[#147a4b]">{order.orderStatus.replace(/_/g," ")}</p></Link>)}</div>:<div className="grid min-h-56 place-items-center text-center"><div><ShoppingBag className="mx-auto text-[#9aa6b3]"/><p className="mt-3 font-bold text-[#0b1f3a]">No student orders yet</p></div></div>}</section>
    <section className="rounded-2xl border border-[#dfe6ec] bg-white p-5"><h2 className="text-lg font-extrabold text-[#0b1f3a]">Real content status</h2><div className="mt-5 space-y-4">{[[FileText,"Materials",materials.length,"/admin/materials"],[GraduationCap,"Programs",programs.length,"/admin/programs"],[BookMarked,"Courses",courses.length,"/admin/courses"],[Newspaper,"Blog posts",posts.length,"/admin/blog-posts"]].map(([Icon,label,count,href])=>{const I=Icon as typeof FileText;return <Link key={label as string} href={href as string} className="flex items-center gap-3 rounded-xl border border-[#edf1f4] p-3 hover:bg-[#f8fafb]"><span className="grid size-9 place-items-center rounded-xl bg-[#eaf6ef] text-[#147a4b]"><I size={17}/></span><span className="flex-1 text-sm font-bold text-[#405169]">{label as string}</span><span className="text-lg font-extrabold text-[#0b1f3a]">{count as number}</span></Link>})}</div><div className="mt-6 border-t border-[#edf1f4] pt-5"><h3 className="text-sm font-extrabold text-[#0b1f3a]">Quick actions</h3><div className="mt-3 space-y-2"><Link href="/admin/materials" className="flex items-center justify-between rounded-xl bg-[#147a4b] px-4 py-3 text-sm font-bold text-white"><span className="flex items-center gap-2"><FilePlus2 size={17}/>Add material</span><ArrowRight size={16}/></Link><Link href="/admin/assignment-dates" className="flex items-center justify-between rounded-xl border border-[#d7e0e7] px-4 py-3 text-sm font-bold text-[#405169]"><span className="flex items-center gap-2"><CalendarDays size={17}/>Update dates</span><ArrowRight size={16}/></Link></div></div></section></div>
  </>;
}
