import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { getPublicBlog } from "@/lib/public-content";
import { formatDate } from "@/lib/utils";
import { SITE_URL } from "@/lib/constants";
type Props={params:Promise<{slug:string}>};
export const dynamic="force-dynamic";
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const post=await getPublicBlog(slug);return post?{title:post.seoTitle||post.title,description:post.metaDescription||post.excerpt,alternates:{canonical:`/blog/${slug}`},openGraph:{type:"article",title:post.title,description:post.excerpt}}:{}}
export default async function Page({params}:Props){const {slug}=await params;const post=await getPublicBlog(slug);if(!post)notFound();const schema={"@context":"https://schema.org","@type":"Article",headline:post.title,datePublished:post.publishDate,dateModified:post.updatedAt,author:{"@type":"Organization","name":post.author},publisher:{"@type":"Organization","name":"Sindh Education Stuff"},mainEntityOfPage:`${SITE_URL}/blog/${post.slug}`};return <article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><header className="bg-[#f4f7f9] py-14 md:py-20"><div className="container-site max-w-4xl"><Breadcrumbs items={[{label:"Blog",href:"/blog"},{label:post.title}]}/><p className="mt-10 text-xs font-bold uppercase tracking-[.1em] text-[#147a4b]">{post.category}</p><h1 className="mt-4 text-[clamp(2.5rem,5vw,4.8rem)] font-extrabold leading-[1] tracking-[-.055em] text-[#0b1f3a]">{post.title}</h1><p className="mt-6 text-lg leading-8 text-[#607086]">{post.excerpt}</p><p className="mt-7 text-sm font-semibold text-[#405169]">By {post.author} · Updated {formatDate(post.updatedAt)} · {post.readTime}</p></div></header><div className="container-site max-w-3xl py-16"><div className="rich-content whitespace-pre-line"><p>{post.content}</p></div></div></article>}
