import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Download, LockKeyhole } from "lucide-react";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { MaterialCard } from "@/components/MaterialCard";
import { getPublicMaterial, getPublicMaterials } from "@/lib/public-content";
import { formatDate } from "@/lib/utils";

type Props={params:Promise<{slug:string}>};
export const dynamic="force-dynamic";
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const item=await getPublicMaterial(slug);return item?{title:item.seoTitle||item.title,description:item.metaDescription||item.description,alternates:{canonical:`/materials/${slug}`}}:{}}
export default async function Page({params}:Props){const {slug}=await params;const item=await getPublicMaterial(slug);if(!item)notFound();const related=(await getPublicMaterials()).filter(value=>value.slug!==item.slug&&value.category===item.category).slice(0,3);return <><header className="bg-[#f4f7f9] py-14 md:py-20"><div className="container-site"><Breadcrumbs items={[{label:"Resources",href:"/resources"},{label:item.title}]}/><div className="mt-8 grid items-end gap-10 lg:grid-cols-[1fr_300px]"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#147a4b]">{item.category} · {item.program}</p><h1 className="mt-4 max-w-4xl text-[clamp(2.5rem,5vw,4.6rem)] font-extrabold leading-[1] tracking-[-.055em] text-[#0b1f3a]">{item.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#607086]">{item.description}</p></div><div className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm text-[#607086]">Course</p><p className="mt-1 text-xl font-extrabold text-[#0b1f3a]">{item.courseCode}</p><p className="mt-4 text-sm text-[#607086]">Updated {formatDate(item.updatedAt)}</p>{item.isFree&&item.fileUrl?<a href={item.fileUrl} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#147a4b] px-5 py-3.5 font-bold text-white"><Download size={18}/>Download free guide</a>:<Link href={`/order-help?material=${item.slug}`} className="mt-6 flex items-center justify-center gap-2 rounded-xl bg-[#147a4b] px-5 py-3.5 font-bold text-white"><LockKeyhole size={18}/>Order Help{item.price?` · PKR ${item.price}`:""}</Link>}</div></div></div></header><section className="section"><div className="container-site max-w-4xl"><div className="rich-content whitespace-pre-line"><h2>About this material</h2><p>{item.content||item.description}</p><h2>Responsible use</h2><p>Use this material for learning, reference and formatting support. Prepare your own original submission according to current university rules.</p></div></div></section>{related.length?<section className="section bg-[#f4f7f9]"><div className="container-site"><h2 className="section-title">Related material</h2><div className="mt-10 grid gap-8 md:grid-cols-3">{related.map(value=><MaterialCard key={value.slug} item={value}/>)}</div></div></section>:null}</>}
